# Generated by Django 2.2 on 2020-02-18 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pruebas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompartirModel',
            fields=[
                ('numero_compartido', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
