# Generated by Django 2.2 on 2020-02-22 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0004_compartirmodel_yo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartirmodel',
            name='tag_a_compartir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pruebas.TagModel'),
        ),
    ]
