# Generated by Django 2.2 on 2020-02-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0005_auto_20200222_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartirmodel',
            name='usuario_a_compartir',
            field=models.TextField(default='-'),
        ),
    ]
