# Generated by Django 2.2 on 2020-04-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0007_auto_20200317_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartirmodel',
            name='yo',
            field=models.IntegerField(null=True),
        ),
    ]
