# Generated by Django 3.0 on 2020-05-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0009_auto_20200503_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativamodel',
            old_name='id',
            new_name='id_alternativa',
        ),
    ]
