# Generated by Django 3.0 on 2020-05-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0010_auto_20200503_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativamodel',
            name='dibujo',
            field=models.TextField(null=True),
        ),
    ]
