# Generated by Django 3.0 on 2020-05-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0011_auto_20200505_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntamodel',
            name='alternativa',
        ),
        migrations.AddField(
            model_name='alternativamodel',
            name='enunciado_alternativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pruebas.PreguntaModel'),
        ),
    ]
