# Generated by Django 3.0 on 2020-05-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0012_auto_20200505_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntamodel',
            name='explicacion',
            field=models.TextField(null=True),
        ),
    ]
