# Generated by Django 3.2.12 on 2022-02-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0013_preguntamodel_explicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntamodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='preguntamodel',
            name='tag',
            field=models.ManyToManyField(to='pruebas.TagModel'),
        ),
    ]
