# Generated by Django 2.2 on 2019-08-15 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionModel',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.TextField()),
                ('rbd', models.IntegerField()),
                ('correo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institucion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registro.InstitucionModel')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
